name: Upwatch Cron Job

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Upwatch Cron
        run: curl -X GET "https://up-watch.vercel.app"
